### ISSUE TITLE
TinderSwipe using VideoView instead of ImageView?

### ISSUE THREAD

**Issue by BastianMeyerPremorrow** [janishar/PlaceHolderView#151]
Hello! 
This library looks promising but I have a question:

Is it possible to make swipe cards but with a VideoView? 
And only the top card should play. Is there a function to solve this?

**Comment by janishar** [comment]
Yes videoview can be used.
use can use `@SwipeHead` callback to start playing the video view currently on top:
Refer the doc: https://janishar.com/PlaceHolderView/docs/sphv-view-definition.html#top-of-stack-callback

**Comment by SaurabhGaddelpalliwar** [comment]
Sir i am using VideoView instead of ImageView ,I start the videoview at SwipeHead but its play 3 position video not first position, please help as soon as possible. And using only Image its work proper but when I use videoView its behavior  changes, not playing first video, its play 3 position video and swipe also 3 position video not first. please help me out of this kind of issue
