### ISSUE TITLE
Swipe movement not smooth

### ISSUE THREAD

**Issue by Sroka** [janishar/PlaceHolderView#46]
First of all, thanks for this great library, really appreciate it. But I have a problem with SwipePlaceHolderView. The movement of the card is not smooth. It jerks when and it is especially visible when going through horizontal and vertical axis.

I recorded a video to illustrate the issue:
https://gfycat.com/gifs/detail/NaughtyHarshEastrussiancoursinghounds

**Comment by janishar** [comment]
Thank you so much. 
I will look into this issue and try to make the transition smooth.

Meanwhile you can remove the rotation.

```java
mSwipeView.getBuilder()
        .setSwipeDecor(new SwipeDecor()
        .setSwipeRotationAngle(0)
```

**Comment by Tokimu** [comment]
I'm having exactly the same issue, with rotation angle set to 0 it works smooth but not doesn't look so spectacular anymore :)

**Comment by janishar** [comment]
@Sroka @Tokimu I have release 0.7.1 version with solution.
Please refer to the below release note for more information.
https://github.com/janishar/PlaceHolderView/releases/tag/0.7.1

**Comment by Sroka** [comment]
@janishar Thank you very much. I am going to test it in coming days and will let you know how it is working now

**Comment by Tokimu** [comment]
Thanks so much for this! It works much better but still i have this feeling like there is one point on the screen that controls card rotation. The problem is when i swipe fast through that point then the card keeps rotation from the wrong side but when i do it slowly, it will change. I was also checking this library for card movement: https://android-arsenal.com/details/1/6075 It looks more smooth to me but i prefer your project more in general :)
